language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - ~/.cache
before_script:
  - npm install
  - cd packages/mirador3-core
  - npm install
  - cd ../mirador3-common
  - npm install
  - cd ../mirador3-app-base
  - npm install
  - cd ../mirador3-e2e-tests
  - npm install
  - cd ../..
  - lerna run build
script:
  - lerna run test --stream
  - cd packages/mirador3-e2e-tests
  - npm run cypress:record
