language: node_js
node_js:
  - "node"
before_script:
  - npm install
  - cd packages/mirador3-core
  - npm install
  - cd ../mirador3-common
    npm install
  - cd ../mirador3-app
  - npm install
  - cd ../..
  - lerna run build
script: lerna run test --stream
