language: node_js
node_js:
  - "8"
before_script:
  - npm install
  - cd packages/mirador3-core
  - npm install
  - cd ../mirador3-app
  - npm install
  - cd ../..
  - lerna run build
script: lerna run test --stream
